version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewords-app
    restart: always
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
